### ISSUE TITLE
Sling Error after component creation

### ISSUE THREAD

**Issue by milenaleksandrov** [adobe/aem-component-generator#18]
I follow up all steps, but at the end I always get this error when I drop my component: 
`Error during include of component '/apps/wdm/components/content/wdm-demo-comp'Error Message:
org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: org.apache.sling.scripting.sightly.SightlyException: Compilation errors in org/apache/sling/scripting/sightly/apps/wdm/components/content/wdm__002d__demo__002d__comp/wdm__002d__demo__002d__comp_html.java:
Line 28, column 1292 : Only a type can be imported. com.aem.wdm.train.core.models.WdmDemoComp resolves to a package
Line 44, column 1925 : WdmDemoComp cannot be resolved to a typeProcessing Info:

Page=/content/wdm/en/about-usResource Path=/content/wdm/en/about-us/jcr:content/root/responsivegrid/wdm_demo_compCell=wdm-demo-compCell Search Path=page|basicpage/root|responsivegrid/responsivegrid/wdm-demo-compComponent Path=/apps/wdm/components/content/wdm-demo-comp
Sling Request Progress:
      0 TIMER_START{Request Processing}
      2 COMMENT timer_end format is {<elapsed microseconds>,<timer name>} <optional message>
      6 LOG Method=GET, PathInfo=null
      7 TIMER_START{handleSecurity}
   1072 TIMER_END{1063,handleSecurity} authenticator org.apache.sling.auth.core.impl.SlingAuthenticator@db1ed68 returns true
   1445 TIMER_START{ResourceResolution}
   1593 TIMER_END{145,ResourceResolution} URI=/content/wdm/en/about-us/jcr:content/root/responsivegrid/wdm_demo_comp.html resolves to Resource=JcrNodeResource, type=wdm/components/content/wdm-demo-comp, superType=null, path=/content/wdm/en/about-us/jcr:content/root/responsivegrid/wdm_demo_comp
   1607 LOG Resource Path Info: SlingRequestPathInfo: path='/content/wdm/en/about-us/jcr:content/root/responsivegrid/wdm_demo_comp', selectorString='null', extension='html', suffix='null'
   1608 TIMER_START{ServletResolution}
   1611 TIMER_START{resolveServlet(/content/wdm/en/about-us/jcr:content/root/responsivegrid/wdm_demo_comp)}
   1627 TIMER_END{15,resolveServlet(/content/wdm/en/about-us/jcr:content/root/responsivegrid/wdm_demo_comp)} Using servlet /apps/wdm/components/content/wdm-demo-comp/wdm-demo-comp.html
   1630 TIMER_END{21,ServletResolution} URI=/content/wdm/en/about-us/jcr:content/root/responsivegrid/wdm_demo_comp.html handled by Servlet=/apps/wdm/components/content/wdm-demo-comp/wdm-demo-comp.html
   1636 LOG Applying Requestfilters
   1638 LOG Calling filter: com.adobe.granite.resourceresolverhelper.impl.ResourceResolverHelperImpl
   1643 LOG Calling filter: org.apache.sling.security.impl.ContentDispositionFilter
   1645 LOG Calling filter: org.apache.sling.i18n.impl.I18NFilter
   1646 LOG Calling filter: com.adobe.granite.httpcache.impl.InnerCacheFilter
   1653 LOG Calling filter: org.apache.sling.rewriter.impl.RewriterFilter
   1655 LOG Calling filter: com.adobe.cq.mcm.campaign.servlets.CampaignCopyTracker
   1657 LOG Calling filter: com.adobe.cq.history.impl.HistoryRequestFilter
   1972 LOG Calling filter: com.day.cq.wcm.core.impl.WCMRequestFilter
   1987 LOG Calling filter: com.adobe.cq.wcm.core.components.internal.servlets.CoreFormHandlingServlet
   1991 LOG Calling filter: com.adobe.granite.optout.impl.OptOutFilter
   1996 LOG Calling filter: com.day.cq.wcm.foundation.forms.impl.FormsHandlingServlet
   1999 LOG Calling filter: com.adobe.cq.social.commons.cors.CORSAuthenticationFilter
   2003 LOG Calling filter: org.apache.sling.engine.impl.debug.RequestProgressTrackerLogFilter
   2005 LOG Calling filter: com.adobe.community.core.filters.LoggingFilter
   2009 LOG Calling filter: com.day.cq.wcm.mobile.core.impl.redirect.RedirectFilter
   2012 LOG Calling filter: com.day.cq.wcm.core.impl.AuthoringUIModeServiceImpl
   2233 LOG Calling filter: com.adobe.granite.csrf.impl.CSRFFilter
   2238 LOG Calling filter: com.adobe.granite.rest.assets.impl.AssetContentDispositionFilter
   2286 LOG Calling filter: com.adobe.granite.requests.logging.impl.RequestLoggerImpl
   2295 LOG Calling filter: com.adobe.granite.rest.impl.servlet.ApiResourceFilter
   2352 LOG Calling filter: com.adobe.cq.social.ugcbase.security.impl.SaferSlingPostServlet
   2355 LOG Calling filter: com.day.cq.wcm.core.impl.warp.TimeWarpFilter
   2362 LOG Calling filter: com.day.cq.dam.core.impl.assetlinkshare.AdhocAssetShareAuthHandler
   2365 LOG Calling filter: com.day.cq.dam.core.impl.servlet.ActivityRecordHandler
   2380 LOG Applying Componentfilters
   2381 LOG Calling filter: com.day.cq.personalization.impl.TargetComponentFilter
   2384 LOG Calling filter: com.day.cq.wcm.core.impl.PageLockFilter
   2386 LOG Calling filter: com.day.cq.wcm.core.impl.WCMComponentFilter
   4731 LOG Found processor for post processing ProcessorConfiguration: {contentTypes=[text/html], order=-1, active=true, valid=true, processErrorResponse=true, pipeline=(generator=Config(type=htmlparser, config={}), transformers=(Config(type=linkchecker, config={}), Config(type=mobile, config=JcrPropertyMap [node=Node[NodeDelegate{tree=/libs/cq/config/rewriter/default/transformer-mobile: { jcr:primaryType = nt:unstructured, component-optional = true}}], values={jcr:primaryType=nt:unstructured, component-optional=true}]), Config(type=mobiledebug, config=JcrPropertyMap [node=Node[NodeDelegate{tree=/libs/cq/config/rewriter/default/transformer-mobiledebug: { jcr:primaryType = nt:unstructured, component-optional = true}}], values={jcr:primaryType=nt:unstructured, component-optional=true}]), Config(type=contentsync, config=JcrPropertyMap [node=Node[NodeDelegate{tree=/libs/cq/config/rewriter/default/transformer-contentsync: { jcr:primaryType = nt:unstructured, component-optional = true}}], values={jcr:primaryType=nt:unstructured, component-optional=true}]), serializer=Config(type=htmlwriter, config={}))}
   5891 LOG Calling filter: com.day.cq.wcm.core.impl.WCMDebugFilter
   5911 TIMER_START{/apps/wdm/components/content/wdm-demo-comp/wdm-demo-comp.html#0}
  31059 LOG SCRIPT ERROR: org.apache.sling.scripting.sightly.SightlyException: Compilation errors in org/apache/sling/scripting/sightly/apps/wdm/components/content/wdm__002d__demo__002d__comp/wdm__002d__demo__002d__comp_html.java:/Line 28, column 1292 : Only a type can be imported. com.aem.wdm.train.core.models.WdmDemoComp resolves to a package/Line 44, column 1925 : WdmDemoComp cannot be resolved to a type
  31095 TIMER_END{25182,/apps/wdm/components/content/wdm-demo-comp/wdm-demo-comp.html#0}
  33061 TIMER_END{33059,Request Processing} Dumping SlingRequestProgressTracker Entries

Full Exception:
org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: org.apache.sling.scripting.sightly.SightlyException: Compilation errors in org/apache/sling/scripting/sightly/apps/wdm/components/content/wdm__002d__demo__002d__comp/wdm__002d__demo__002d__comp_html.java:
Line 28, column 1292 : Only a type can be imported. com.aem.wdm.train.core.models.WdmDemoComp resolves to a package
Line 44, column 1925 : WdmDemoComp cannot be resolved to a type
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.service(DefaultSlingScript.java:510)
	at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:552)
	at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:44)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77)
	at com.day.cq.wcm.core.impl.WCMDebugFilter.doFilterWithErrorHandling(WCMDebugFilter.java:192)
	at com.day.cq.wcm.core.impl.WCMDebugFilter.doFilter(WCMDebugFilter.java:159)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at com.day.cq.wcm.core.impl.WCMComponentFilter.doFilter(WCMComponentFilter.java:278)
	at com.day.cq.wcm.core.impl.WCMComponentFilter.filterRootInclude(WCMComponentFilter.java:373)
	at com.day.cq.wcm.core.impl.WCMComponentFilter.doFilter(WCMComponentFilter.java:190)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at com.day.cq.wcm.core.impl.PageLockFilter.doFilter(PageLockFilter.java:91)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at com.day.cq.personalization.impl.TargetComponentFilter.doFilter(TargetComponentFilter.java:96)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at org.apache.sling.engine.impl.SlingRequestProcessorImpl.processComponent(SlingRequestProcessorImpl.java:282)
	at org.apache.sling.engine.impl.filter.RequestSlingFilterChain.render(RequestSlingFilterChain.java:49)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77)
	at com.day.cq.dam.core.impl.servlet.ActivityRecordHandler.doFilter(ActivityRecordHandler.java:154)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:73)
	at com.day.cq.dam.core.impl.assetlinkshare.AdhocAssetShareAuthHandler.doFilter(AdhocAssetShareAuthHandler.java:437)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:73)
	at com.day.cq.wcm.core.impl.warp.TimeWarpFilter.doFilter(TimeWarpFilter.java:109)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at com.adobe.cq.social.ugcbase.security.impl.SaferSlingPostServlet.doFilter(SaferSlingPostServlet.java:114)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:73)
	at com.adobe.granite.rest.impl.servlet.ApiResourceFilter.doFilter(ApiResourceFilter.java:70)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at com.adobe.granite.requests.logging.impl.RequestLoggerImpl.doFilter(RequestLoggerImpl.java:134)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at com.adobe.granite.rest.assets.impl.AssetContentDispositionFilter.doFilter(AssetContentDispositionFilter.java:96)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at com.adobe.granite.csrf.impl.CSRFFilter.doFilter(CSRFFilter.java:217)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at com.day.cq.wcm.core.impl.AuthoringUIModeServiceImpl.doFilter(AuthoringUIModeServiceImpl.java:372)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at com.day.cq.wcm.mobile.core.impl.redirect.RedirectFilter.doFilter(RedirectFilter.java:248)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at com.adobe.community.core.filters.LoggingFilter.doFilter(LoggingFilter.java:56)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at org.apache.sling.engine.impl.debug.RequestProgressTrackerLogFilter.doFilter(RequestProgressTrackerLogFilter.java:107)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:73)
	at com.adobe.cq.social.commons.cors.CORSAuthenticationFilter.doFilter(CORSAuthenticationFilter.java:91)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at com.day.cq.wcm.foundation.forms.FormsHandlingServletHelper.handleFilter(FormsHandlingServletHelper.java:226)
	at com.day.cq.wcm.foundation.forms.impl.FormsHandlingServlet.doFilter(FormsHandlingServlet.java:138)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at com.adobe.granite.optout.impl.OptOutFilter.doFilter(OptOutFilter.java:76)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at com.day.cq.wcm.foundation.forms.FormsHandlingServletHelper.handleFilter(FormsHandlingServletHelper.java:226)
	at com.adobe.cq.wcm.core.components.internal.servlets.CoreFormHandlingServlet.doFilter(CoreFormHandlingServlet.java:126)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at com.day.cq.wcm.core.impl.WCMRequestFilter.doFilter(WCMRequestFilter.java:90)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at com.adobe.cq.history.impl.HistoryRequestFilter.doFilter(HistoryRequestFilter.java:122)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at com.adobe.cq.mcm.campaign.servlets.CampaignCopyTracker.doFilter(CampaignCopyTracker.java:100)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at org.apache.sling.rewriter.impl.RewriterFilter.doFilter(RewriterFilter.java:87)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at com.adobe.granite.httpcache.impl.InnerCacheFilter.doFilter(InnerCacheFilter.java:81)
	at com.adobe.granite.httpcache.impl.InnerCacheFilter.doFilter(InnerCacheFilter.java:60)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:131)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at org.apache.sling.security.impl.ContentDispositionFilter.doFilter(ContentDispositionFilter.java:152)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:73)
	at com.adobe.granite.resourceresolverhelper.impl.ResourceResolverHelperImpl.doFilter(ResourceResolverHelperImpl.java:83)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at org.apache.sling.engine.impl.SlingRequestProcessorImpl.doProcessRequest(SlingRequestProcessorImpl.java:151)
	at org.apache.sling.engine.impl.SlingMainServlet.service(SlingMainServlet.java:234)
	at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:120)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:86)
	at org.apache.sling.security.impl.ReferrerFilter.doFilter(ReferrerFilter.java:328)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81)
	at com.adobe.granite.license.impl.LicenseCheckFilter.doFilter(LicenseCheckFilter.java:308)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81)
	at org.apache.felix.http.sslfilter.internal.SslFilter.doFilter(SslFilter.java:96)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81)
	at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:131)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81)
	at org.apache.sling.featureflags.impl.FeatureManager.doFilter(FeatureManager.java:116)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81)
	at org.apache.sling.engine.impl.log.RequestLoggerFilter.doFilter(RequestLoggerFilter.java:72)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81)
	at org.apache.sling.engine.impl.parameters.RequestParameterSupportConfigurer.doFilter(RequestParameterSupportConfigurer.java:63)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:81)
	at org.apache.felix.http.base.internal.dispatch.Dispatcher$1.doFilter(Dispatcher.java:147)
	at org.apache.felix.http.base.internal.whiteboard.WhiteboardManager.invokePreprocessors(WhiteboardManager.java:1000)
	at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:91)
	at org.apache.felix.http.base.internal.dispatch.DispatcherServlet.service(DispatcherServlet.java:49)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.sling.scripting.sightly.SightlyException: org.apache.sling.scripting.sightly.SightlyException: Compilation errors in org/apache/sling/scripting/sightly/apps/wdm/components/content/wdm__002d__demo__002d__comp/wdm__002d__demo__002d__comp_html.java:
Line 28, column 1292 : Only a type can be imported. com.aem.wdm.train.core.models.WdmDemoComp resolves to a package
Line 44, column 1925 : WdmDemoComp cannot be resolved to a type
	at org.apache.sling.scripting.sightly.impl.engine.SightlyJavaCompilerService.compileSource(SightlyJavaCompilerService.java:183)
	at org.apache.sling.scripting.sightly.impl.engine.SightlyScriptEngine.internalCompile(SightlyScriptEngine.java:157)
	at org.apache.sling.scripting.sightly.impl.engine.SightlyScriptEngine.compile(SightlyScriptEngine.java:89)
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.call(DefaultSlingScript.java:379)
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.eval(DefaultSlingScript.java:184)
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.service(DefaultSlingScript.java:491)
	... 125 more
Caused by: org.apache.sling.scripting.sightly.SightlyException: Compilation errors in org/apache/sling/scripting/sightly/apps/wdm/components/content/wdm__002d__demo__002d__comp/wdm__002d__demo__002d__comp_html.java:
Line 28, column 1292 : Only a type can be imported. com.aem.wdm.train.core.models.WdmDemoComp resolves to a package
Line 44, column 1925 : WdmDemoComp cannot be resolved to a type
	at org.apache.sling.scripting.sightly.impl.engine.SightlyJavaCompilerService.compileSource(SightlyJavaCompilerService.java:173)
	... 130 more

Day Communique 5 WCM Core Implementation / 5.11.218 ( (c) Adobe Systems Incorporated ) running on ApacheSling/2.6 (jetty/9.3.22.v20171030, Java HotSpot(TM) 64-Bit Server VM 1.8.0_161, Windows 10 10.0 amd64)`

**Comment by HitmanInWis** [comment]
This would likely be caused by your java code bundle (with sling models) not deploying.  Have you checked `/system/console/bundles` to verify that your bundles is "Active" (not "Installed")?  If it is just "Installed", can you post what dependencies are missing?  What version of AEM are you running?

**Comment by milenaleksandrov** [comment]
Hi there,

That was fast :) 
Here it is, and you was correct it was "Installed":
com.day.cq.wcm.foundation,version=[5.22,6) -- Cannot be resolved
javax.annotation,version=[1.3,2) -- Cannot be resolved
org.apache.sling.api.resource,version=[2.11,3) -- Cannot be resolved

I'll try to install them and try again.

Thank you!
Milen Aleksandrov

**Comment by HitmanInWis** [comment]
What version of AEM are you running, including service packs?  you may need to have at least 6.3 with SP3 installed.

**Comment by milenaleksandrov** [comment]
Sorry, the version I'm using is pure 6.4 with no SP installed.

**Comment by HitmanInWis** [comment]
AEM 6.4 is up to SP4 now - can you try installing SP4 and see if this resolves your issue?

Your version of AEM after installing SP4 should show as 6.4.4

**Comment by maleksandrov** [comment]
Hi HitmanInWis,

This solved my issue. 

Thank you for your fast support. 

Best,
Milen

**Comment by HitmanInWis** [comment]
Absolutely, glad to help!

**Comment by midhun1909** [comment]
Hi,

I am facing the same issue, but how can I check the dependencies and AEM version I am using is 6.5.7

**Comment by HitmanInWis** [comment]
I would definitely check that all of your bundles are running via /system/console/bundles.  I've tested running generated components on AEM 6.5.7 personally and they work correctly, so there must be something more to the picture.  Do you have other components with sling models that working correctly?

**Comment by ABASK05** [comment]
Hi,

I have setup publish instance in local. I am also facing the kind of same issue while loading any of my pages, AEM version i am using is 6.5.4. i have checked in osgi there is no dependency for the bundle, it is active. please help to identify which service package needs to be installed to resolve the issue.

**Errors i am getting**
org.apache.sling.scripting.sightly.SightlyException: org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: org.apache.sling.api.SlingException: Cannot get DefaultSlingScript:
	at com.adobe.cq.sightly.WCMScriptHelper.includeScript(WCMScriptHelper.java:227) [com.adobe.cq.sightly.cq-wcm-sightly-extension:1.6.0]
	at com.adobe.cq.sightly.internal.extensions.IncludeExtension.call(IncludeExtension.java:72) [com.adobe.cq.sightly.cq-wcm-sightly-extension:1.6.0]
	at org.apache.sling.scripting.sightly.impl.engine.runtime.RenderContextImpl.call(RenderContextImpl.java:77) [org.apache.sling.scripting.sightly:1.1.2.1_4_0]

**Comment by HitmanInWis** [comment]
Do you have WCM Core components installed and do those components work correctly?  Let's start there.

The next thing to try would be to create a fresh project from the AEM archetype, install it, and see if the components inside the archetype work.

If all of that works, I would then try creating your generated component _inside_ the archetype project, and see if that also works.

Assuming all those things work, I would then compare your project setup (particularly pom files) to the archetype to see what differences there are.
